version: '3.5'

services:
  database:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'facoffee'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - facoffee-database:/var/lib/mysql
      - ./db/CreateInitialInformation.sql:/docker-entrypoint-initdb.d/CreateInitialInformation.sql
volumes:
  facoffee-database: